name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Run IC tests
      run: |
        cd tests
        chmod +x run_test_ic.sh
        ./run_test_ic.sh
      
    - name: Install package and run unit tests
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
        if [ -d "kybra_simple_shell/tests/" ]; then
          pytest kybra_simple_shell/tests/
        else
          echo "No tests directory found at kybra_simple_shell/tests/"
          echo "Current directory contents:"
          ls -la
          echo "\nkybra_simple_shell directory contents:"
          ls -la kybra_simple_shell/ || echo "kybra_simple_shell/ not found"
        fi
